os: Visual Studio 2015
platform:
  - x64
  - x86
configuration:
  - Release
matrix:
  fast_finish: true

environment:
  matrix:
    # x64
    - nodejs_version: 10
      msvs_toolset: 14
    - nodejs_version: 11
      msvs_toolset: 14
    - nodejs_version: 12
      msvs_toolset: 14
    - nodejs_version: 13
      msvs_toolset: 14

install:
  - .\scripts\winci.bat

build: OFF
test: OFF
deploy: OFF
